version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydlala
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/mydlala.sql	
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  